# Generated by Django 6.0.5 on 2026-05-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0002_property_owner_tenant_owner_transaction_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_name', models.CharField(default='System Administrator', max_length=100)),
                ('email', models.EmailField(default='admin@equiestate.local', max_length=254)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='property',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='owner',
        ),
    ]
