# Generated by Django 6.0.5 on 2026-05-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0003_systemprofile_remove_property_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='current_electric_reading',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tenant',
            name='current_water_reading',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tenant',
            name='previous_electric_reading',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tenant',
            name='previous_water_reading',
            field=models.FloatField(default=0.0),
        ),
    ]
